INSERT INTO clanlite_alert VALUES (16, '-1', 'Version Publique de ClanLite', 'oui');
INSERT INTO clanlite_config VALUES ('langue', 'Francais');
INSERT INTO clanlite_config VALUES ('reglement', '');
INSERT INTO clanlite_config VALUES ('master_mail', 'narfight@clanlite.org');
INSERT INTO clanlite_config VALUES ('site_domain', 'http://127.0.0.1');
INSERT INTO clanlite_config VALUES ('time_cook', '2');
INSERT INTO clanlite_config VALUES ('nbr_membre', '1');
INSERT INTO clanlite_config VALUES ('id_membre_match', '');
INSERT INTO clanlite_config VALUES ('list_game_serveur', 'oui');
INSERT INTO clanlite_config VALUES ('url_forum', 'http://forum.clanlite.org');
INSERT INTO clanlite_config VALUES ('compteur', '1');
INSERT INTO clanlite_config VALUES ('msg_bienvenu', '');
INSERT INTO clanlite_config VALUES ('inscription', '2');
INSERT INTO clanlite_config VALUES ('tag', '[CL]');
INSERT INTO clanlite_config VALUES ('nom_clan', '[Clan Lite - Home]');
INSERT INTO clanlite_config VALUES ('limite_inscription', '24');
INSERT INTO clanlite_config VALUES ('version', '1.23.01.2005');
INSERT INTO clanlite_config VALUES ('objet_par_page', '10');
INSERT INTO clanlite_config VALUES ('site_path', '/clanlite/');
INSERT INTO clanlite_config VALUES ('raport_error', '1');
INSERT INTO clanlite_config VALUES ('recrutement_alert', '1');
INSERT INTO clanlite_config VALUES ('send_mail', 'mail');
INSERT INTO clanlite_config VALUES ('smtp_ip', 'localhost');
INSERT INTO clanlite_config VALUES ('smtp_port', '25');
INSERT INTO clanlite_config VALUES ('smtp_code', '');
INSERT INTO clanlite_config VALUES ('smtp_login', '');
INSERT INTO clanlite_config VALUES ('skin', '');
INSERT INTO clanlite_config VALUES ('get_version', '1');
INSERT INTO clanlite_config VALUES ('scan_game_server', 'udp');
INSERT INTO clanlite_config VALUES ('show_grade', '1');
INSERT INTO clanlite_custom_menu VALUES (1, 1, 'boutton_news', 'service/index_pri.php', '0', '0', '0', 0, '1');
INSERT INTO clanlite_custom_menu VALUES (2, 2, 'boutton_liste_membres_groupe', 'service/liste-des-membres-groupe.php', '0', '0', '0', 0, '1');
INSERT INTO clanlite_custom_menu VALUES (3, 3, 'boutton_forum', 'url_forum', '0', '0', '0', 0, '1');
INSERT INTO clanlite_custom_menu VALUES (4, 4, 'boutton_match', 'service/match.php', '0', '0', '0', 0, '1');
INSERT INTO clanlite_custom_menu VALUES (5, 5, 'boutton_calendrier', 'service/calendrier.php', '0', '0', '0', 0, '1');
INSERT INTO clanlite_custom_menu VALUES (6, 6, 'boutton_reglement', 'service/reglement.php', '0', '0', '0', 0, '1');
INSERT INTO clanlite_custom_menu VALUES (7, 7, 'boutton_result_match', 'service/rapport_match.php', '0', '0', '0', 0, '1');
INSERT INTO clanlite_custom_menu VALUES (8, 8, 'boutton_telecharger', 'service/download.php', '0', '0', '0', 0, '1');
INSERT INTO clanlite_custom_menu VALUES (9, 9, 'boutton_liens', 'service/liens.php', '0', '0', '0', 0, '1');
INSERT INTO clanlite_custom_menu VALUES (10, 10, 'boutton_org_rencontre', 'service/defier.php', '0', '0', '0', 0, '1');
INSERT INTO clanlite_custom_menu VALUES (11, 11, 'Un Bug !?', 'http://mantis.clanlite.org/', '0', '0', '0', 0, 'normal');
INSERT INTO clanlite_custom_menu VALUES (12, 11, 'boutton_liste_game', 'service/serveur_game_list.php', '0', '0', '0', 0, '1');
INSERT INTO clanlite_entrainement VALUES (1, '1117024200', 'Match sur St-lo, pour le code : regarder en privé', 'narfight', 'le code est : mdsfsdfcxvxcwcv');
INSERT INTO clanlite_modules VALUES (1, 2, 'droite', '1', 'MP3', 'cadre_mp3.php', '');
INSERT INTO clanlite_modules VALUES (4, 0, 'gauche', '1', 'Match  à Venir', 'match.php', '');
INSERT INTO clanlite_modules VALUES (5, 1, 'droite', '1', 'Compteur', 'compteur.php', '');
INSERT INTO clanlite_modules VALUES (6, 4, 'droite', '0', 'Serveur MOH', 'serveur_jeux.php', 'serveur_clan');
INSERT INTO clanlite_modules VALUES (7, 5, 'gauche', '1', 'TeamSpeak Luncher', 'connection_teamspeak.php', 'vocal.lna.be|!|7660');
INSERT INTO clanlite_modules VALUES (8, 6, 'gauche', '1', 'Last Match', 'dernier_match.php', '');
INSERT INTO clanlite_modules VALUES (10, 8, 'gauche', '1', 'Training', 'entrainements.php', '');
INSERT INTO clanlite_news VALUES (14, '1079790784', 'Les rapports de match', 'Installation de ClanLite réussie', 'narfight');
INSERT INTO clanlite_section VALUES (1, 'Section n°1', 0, 1);
INSERT INTO clanlite_smilies VALUES (44, ':D', 'BD.gif', 'super heureux', 16, 16);
INSERT INTO clanlite_smilies VALUES (45, ':-D', 'BD.gif', 'super heureux', 16, 16);
INSERT INTO clanlite_smilies VALUES (46, ':grin:', 'BD.gif', 'super heureux', 16, 16);
INSERT INTO clanlite_smilies VALUES (47, ':)', 'normal.gif', 'Heureux', 16, 16);
INSERT INTO clanlite_smilies VALUES (48, ':-)', 'normal.gif', 'Heureux', 16, 16);
INSERT INTO clanlite_smilies VALUES (49, ':smile:', 'normal.gif', 'Heureux', 16, 16);
INSERT INTO clanlite_smilies VALUES (50, ':(', 'triste.gif', 'Pas heureux', 16, 16);
INSERT INTO clanlite_smilies VALUES (51, ':-(', 'triste.gif', 'Pas heureux', 16, 16);
INSERT INTO clanlite_smilies VALUES (52, ':sad:', 'triste.gif', 'Pas heureux', 16, 16);
INSERT INTO clanlite_smilies VALUES (53, ':o', 'surpi.gif', 'Étonné', 16, 16);
INSERT INTO clanlite_smilies VALUES (54, ':-o', 'surpi.gif', 'Étonné', 16, 16);
INSERT INTO clanlite_smilies VALUES (55, ':eek:', 'surpi.gif', 'Choquer', 16, 16);
INSERT INTO clanlite_smilies VALUES (56, ':shock:', 'nonnn-sii.gif', 'Choquer', 16, 16);
INSERT INTO clanlite_smilies VALUES (57, ':?', 'question.gif', 'Confusion', 16, 16);
INSERT INTO clanlite_smilies VALUES (58, ':-?', 'question.gif', 'Confusion', 16, 16);
INSERT INTO clanlite_smilies VALUES (59, ':???:', 'question.gif', 'Confusion', 16, 16);
INSERT INTO clanlite_smilies VALUES (60, '8)', 'fx.gif', 'Cool', 16, 16);
INSERT INTO clanlite_smilies VALUES (61, '8-)', 'fx.gif', 'Cool', 16, 16);
INSERT INTO clanlite_smilies VALUES (62, ':cool:', 'fx.gif', 'Cool', 16, 16);
INSERT INTO clanlite_smilies VALUES (63, 'LOL', 'LOL.gif', 'lol', 16, 16);
INSERT INTO clanlite_smilies VALUES (64, ':x', 'non.gif', 'Mécontent', 16, 16);
INSERT INTO clanlite_smilies VALUES (65, ':-x', 'non.gif', 'Mécontent', 16, 16);
INSERT INTO clanlite_smilies VALUES (66, ':mad:', 'non.gif', 'Mécontent', 16, 16);
INSERT INTO clanlite_smilies VALUES (67, ':P', 'pop.gif', 'Razz', 16, 16);
INSERT INTO clanlite_smilies VALUES (68, ':-p', 'pop.gif', 'Razz', 16, 16);
INSERT INTO clanlite_smilies VALUES (69, ':razz:', 'pop.gif', 'Razz', 16, 16);
INSERT INTO clanlite_smilies VALUES (70, ':oops:', 'confusion.gif', 'Embarassé', 16, 16);
INSERT INTO clanlite_smilies VALUES (71, ':cry:', 'snif.gif', 'Crying or Very sad', 16, 16);
INSERT INTO clanlite_smilies VALUES (72, ':evil:', 'evil.gif', 'Evil or Very Mad', 16, 16);
INSERT INTO clanlite_smilies VALUES (73, ':twisted:', 'evil-heureux.gif', 'Twisted Evil', 16, 16);
INSERT INTO clanlite_smilies VALUES (74, ':roll:', 'ou.gif', 'Chercher', 16, 16);
INSERT INTO clanlite_smilies VALUES (75, ':wink:', 'clinoeil.gif', 'Wink', 16, 16);
INSERT INTO clanlite_smilies VALUES (76, ';)', 'clinoeil.gif', 'Wink', 16, 16);
INSERT INTO clanlite_smilies VALUES (77, ';-)', 'clinoeil.gif', 'Wink', 16, 16);
INSERT INTO clanlite_smilies VALUES (78, ':!:', 'excamation.gif', 'Exclamation', 16, 16);
INSERT INTO clanlite_smilies VALUES (79, ':?:', 'interogation.gif', 'Question', 16, 16);
INSERT INTO clanlite_smilies VALUES (80, ':idea:', 'idee.gif', 'idée', 16, 16);
INSERT INTO clanlite_smilies VALUES (81, ':>:', 'fleche droite.gif', 'fleche', 10, 10);
INSERT INTO clanlite_smilies VALUES (82, ':|', 'neutre.gif', 'Neutral', 16, 16);
INSERT INTO clanlite_smilies VALUES (83, ':-|', 'neutre.gif', 'Neutral', 16, 16);
INSERT INTO clanlite_smilies VALUES (84, ':neutral:', 'neutre.gif', 'Neutral', 16, 16);
INSERT INTO clanlite_smilies VALUES (85, ':<:', 'fleche gauche.gif', 'fleche', 10, 10);
INSERT INTO clanlite_smilies VALUES (86, 'L\'OL', 'lol-pleur.gif', 'trop fort', 16, 16);
INSERT INTO clanlite_smilies VALUES (87, 'zzz', 'zzz.gif', 'dormir', 16, 16);
INSERT INTO clanlite_smilies VALUES (88, '(msn)', 'msn.gif', 'msn messenger', 14, 16);
INSERT INTO clanlite_smilies VALUES (89, '(trillian)', 'trilliangif.gif', 'trillian', 16, 16);
INSERT INTO clanlite_smilies VALUES (90, ':cowboy:', 'vache.gif', 'cowboy', 16, 16);
INSERT INTO clanlite_smilies VALUES (91, '8=', 'supper.gif', 'bordelle de ****', 16, 16);
INSERT INTO clanlite_smilies VALUES (92, 'Bp', 'lunette.gif', 'cool les mecs', 16, 16);
INSERT INTO clanlite_smilies VALUES (93, '<(', 'crever.gif', 'fatiguer', 16, 16);
INSERT INTO clanlite_smilies VALUES (94, ':aie:', 'burq.gif', 'fais mal', 16, 16);
INSERT INTO clanlite_smilies VALUES (95, ':-/', 'heu.gif', 'arf', 16, 16);
INSERT INTO clanlite_smilies VALUES (96, '/!\\', 'attention.gif', 'Attention', 16, 16);
INSERT INTO clanlite_smilies VALUES (97, ':hug:', 'emot-hug.gif', 'je t\'aime toi', 40, 16);
INSERT INTO clanlite_smilies VALUES (98, ':gerbe:', 'emot-puke.gif', 'BUUuuuuuurg', 25, 16);
INSERT INTO clanlite_smilies VALUES (99, ':hihi:', 'sm11.gif', 'hihihihih', 16, 16);
INSERT INTO clanlite_smilies VALUES (100, ':prie:', 'prie.gif', 'Prie', 24, 16);
INSERT INTO clanlite_smilies VALUES (101, ':ho:', 'nonnn-sii.gif', 'hoo la grosse :-D', 16, 16);
INSERT INTO clanlite_smilies VALUES (102, ':bave:', 'emot-drool.gif', 'J\'en bave', 16, 16);
INSERT INTO clanlite_smilies VALUES (103, ':bye:', 'aa.gif', 'Bye mec', 16, 16);
INSERT INTO clanlite_équipe VALUES (1, 'Sniper', 'Les Snipers tout simplement');
INSERT INTO clanlite_équipe VALUES (4, 'Rusher', 'ce sont ceux qui courent relativement vite');