INSERT INTO clanlite_alert VALUES (16, '-1', 'Version Publique de ClanLite', 'oui');
INSERT INTO clanlite_config VALUES ('langue', 'Francais');
INSERT INTO clanlite_config VALUES ('reglement', '');
INSERT INTO clanlite_config VALUES ('master_mail', 'narfight@lna.be');
INSERT INTO clanlite_config VALUES ('site_domain', 'http://127.0.0.1');
INSERT INTO clanlite_config VALUES ('time_cook', '2');
INSERT INTO clanlite_config VALUES ('nbr_membre', '3');
INSERT INTO clanlite_config VALUES ('id_membre_match', '3');
INSERT INTO clanlite_config VALUES ('list_game_serveur', 'oui');
INSERT INTO clanlite_config VALUES ('url_forum', 'http://www.lna.be/');
INSERT INTO clanlite_config VALUES ('compteur', '1181');
INSERT INTO clanlite_config VALUES ('msg_bienvenu', '');
INSERT INTO clanlite_config VALUES ('inscription', '2');
INSERT INTO clanlite_config VALUES ('serveur', '1');
INSERT INTO clanlite_config VALUES ('tag', '[CL]');
INSERT INTO clanlite_config VALUES ('nom_clan', '&lt;Clan Lite&gt; Home');
INSERT INTO clanlite_config VALUES ('limite_inscription', '24');
INSERT INTO clanlite_config VALUES ('version', '1.18.04.2004');
INSERT INTO clanlite_config VALUES ('serveur_game_ip', '69.28.220.158');
INSERT INTO clanlite_config VALUES ('serveur_game_port', '8777');
INSERT INTO clanlite_config VALUES ('serveur_game_info', 'Merci a Aresgames');
INSERT INTO clanlite_config VALUES ('serveur_game_protocol', 'rvnshld');
INSERT INTO clanlite_config VALUES ('objet_par_page', '3');
INSERT INTO clanlite_config VALUES ('site_path', '/clanlite/');
INSERT INTO clanlite_config VALUES ('raport_error', '1');
INSERT INTO clanlite_config VALUES ('recrutement_alert', '1');
INSERT INTO clanlite_config_sond VALUES (1, 'http://anywex.free.fr/medal_fichier/U2%20-%20B-Sides%20-%2004%20-%20Love%20Comes%20Tumbling.mp3', 'TRUE', 'FALSE', 'U2', 'Love Comes Tumbling');
INSERT INTO clanlite_config_sond VALUES (2, 'http://anywex.free.fr/medal_fichier/Dallas%20(version%20fran%e7aise).mp3', 'TRUE', 'TRUE', '???', 'Dallas');
INSERT INTO clanlite_custom_menu VALUES (1, '1', 'Un Bug !?', 'http://www.europubliweb.com/born-to-up/mantis/login_page.php', '', '');
INSERT INTO clanlite_entrainement VALUES (14, '1117024200', 'Match sur St-lo, pour le code : regarder en privé', 'narfight', 'le code est : mdsfsdfcxvxcwcv');
INSERT INTO clanlite_entrainement VALUES (17, '1292108400', 'sdfsdfsdf', 'narfight', 'sdfsdsdfsdf\r\nsdfsdfsdfsdf\r\nsdfsdfsdfsdfsdf');
INSERT INTO clanlite_game_server VALUES (7, '62.4.70.140', 12504, 'q3a');
INSERT INTO clanlite_modules VALUES (1, 2, 'droite', '1', 'MP3', 'cadre_mp3.php', '');
INSERT INTO clanlite_modules VALUES (4, 0, 'gauche', '1', 'Match  à Venir', 'match.php', '');
INSERT INTO clanlite_modules VALUES (5, 1, 'droite', '1', 'Compteur', 'compteur.php', '');
INSERT INTO clanlite_modules VALUES (6, 4, 'droite', '0', 'Serveur MOH', 'serveur_jeux.php', 'serveur_clan');
INSERT INTO clanlite_modules VALUES (7, 5, 'gauche', '1', 'TeamSpeak Luncher', 'connection_teamspeak.php', 'vocal.lna.be|!|7660');
INSERT INTO clanlite_modules VALUES (8, 6, 'gauche', '1', 'Last Match', 'dernier_match.php', '');
INSERT INTO clanlite_modules VALUES (10, 8, 'gauche', '1', 'Training', 'entrainements.php', '');
INSERT INTO clanlite_modules VALUES (11, 0, 'droite', '0', 'Notre Vocal', 'teamspeak_ticker.php', 'http://www.europubliweb.com/born-to-up/ts/ticker_nsd.php|!|http://www.europubliweb.com/born-to-up/ts/');
INSERT INTO clanlite_news VALUES (14, '1079790784', 'Les rapports de match', 'Installation de ClanLite réussie', 'narfight');
INSERT INTO clanlite_section VALUES (1, 'Section n°1', '1');
INSERT INTO clanlite_smilies VALUES (44, ':D', 'BD.gif', 'super heureux', 16, 16);
INSERT INTO clanlite_smilies VALUES (45, ':-D', 'BD.gif', 'super heureux', 16, 16);
INSERT INTO clanlite_smilies VALUES (46, ':grin:', 'BD.gif', 'super heureux', 16, 16);
INSERT INTO clanlite_smilies VALUES (47, ':)', 'normal.gif', 'Heureux', 16, 16);
INSERT INTO clanlite_smilies VALUES (48, ':-)', 'normal.gif', 'Heureux', 16, 16);
INSERT INTO clanlite_smilies VALUES (49, ':smile:', 'normal.gif', 'Heureux', 16, 16);
INSERT INTO clanlite_smilies VALUES (50, ':(', 'triste.gif', 'Pas heureux', 16, 16);
INSERT INTO clanlite_smilies VALUES (51, ':-(', 'triste.gif', 'Pas heureux', 16, 16);
INSERT INTO clanlite_smilies VALUES (52, ':sad:', 'triste.gif', 'Pas heureux', 16, 16);
INSERT INTO clanlite_smilies VALUES (53, ':o', 'surpi.gif', 'Étonné', 16, 16);
INSERT INTO clanlite_smilies VALUES (54, ':-o', 'surpi.gif', 'Étonné', 16, 16);
INSERT INTO clanlite_smilies VALUES (55, ':eek:', 'surpi.gif', 'Choquer', 16, 16);
INSERT INTO clanlite_smilies VALUES (56, ':shock:', 'nonnn-sii.gif', 'Choquer', 16, 16);
INSERT INTO clanlite_smilies VALUES (57, ':?', 'question.gif', 'Confusion', 16, 16);
INSERT INTO clanlite_smilies VALUES (58, ':-?', 'question.gif', 'Confusion', 16, 16);
INSERT INTO clanlite_smilies VALUES (59, ':???:', 'question.gif', 'Confusion', 16, 16);
INSERT INTO clanlite_smilies VALUES (60, '8)', 'fx.gif', 'Cool', 16, 16);
INSERT INTO clanlite_smilies VALUES (61, '8-)', 'fx.gif', 'Cool', 16, 16);
INSERT INTO clanlite_smilies VALUES (62, ':cool:', 'fx.gif', 'Cool', 16, 16);
INSERT INTO clanlite_smilies VALUES (63, 'LOL', 'LOL.gif', 'lol', 16, 16);
INSERT INTO clanlite_smilies VALUES (64, ':x', 'non.gif', 'Mécontent', 16, 16);
INSERT INTO clanlite_smilies VALUES (65, ':-x', 'non.gif', 'Mécontent', 16, 16);
INSERT INTO clanlite_smilies VALUES (66, ':mad:', 'non.gif', 'Mécontent', 16, 16);
INSERT INTO clanlite_smilies VALUES (67, ':P', 'pop.gif', 'Razz', 16, 16);
INSERT INTO clanlite_smilies VALUES (68, ':-p', 'pop.gif', 'Razz', 16, 16);
INSERT INTO clanlite_smilies VALUES (69, ':razz:', 'pop.gif', 'Razz', 16, 16);
INSERT INTO clanlite_smilies VALUES (70, ':oops:', 'confusion.gif', 'Embarasser', 16, 16);
INSERT INTO clanlite_smilies VALUES (71, ':cry:', 'snif.gif', 'Crying or Very sad', 16, 16);
INSERT INTO clanlite_smilies VALUES (72, ':evil:', 'evil.gif', 'Evil or Very Mad', 16, 16);
INSERT INTO clanlite_smilies VALUES (73, ':twisted:', 'evil-heureux.gif', 'Twisted Evil', 16, 16);
INSERT INTO clanlite_smilies VALUES (74, ':roll:', 'ou.gif', 'Chercher', 16, 16);
INSERT INTO clanlite_smilies VALUES (75, ':wink:', 'clinoeil.gif', 'Wink', 16, 16);
INSERT INTO clanlite_smilies VALUES (76, ';)', 'clinoeil.gif', 'Wink', 16, 16);
INSERT INTO clanlite_smilies VALUES (77, ';-)', 'clinoeil.gif', 'Wink', 16, 16);
INSERT INTO clanlite_smilies VALUES (78, ':!:', 'excamation.gif', 'Exclamation', 16, 16);
INSERT INTO clanlite_smilies VALUES (79, ':?:', 'interogation.gif', 'Question', 16, 16);
INSERT INTO clanlite_smilies VALUES (80, ':idea:', 'idee.gif', 'idée', 16, 16);
INSERT INTO clanlite_smilies VALUES (81, ':>:', 'fleche droite.gif', 'fleche', 10, 10);
INSERT INTO clanlite_smilies VALUES (82, ':|', 'neutre.gif', 'Neutral', 16, 16);
INSERT INTO clanlite_smilies VALUES (83, ':-|', 'neutre.gif', 'Neutral', 16, 16);
INSERT INTO clanlite_smilies VALUES (84, ':neutral:', 'neutre.gif', 'Neutral', 16, 16);
INSERT INTO clanlite_smilies VALUES (85, ':<:', 'fleche gauche.gif', 'fleche', 10, 10);
INSERT INTO clanlite_smilies VALUES (86, 'L\'OL', 'lol-pleur.gif', 'trop fort', 16, 16);
INSERT INTO clanlite_smilies VALUES (87, 'zzz', 'zzz.gif', 'dormir', 16, 16);
INSERT INTO clanlite_smilies VALUES (88, '(msn)', 'msn.gif', 'msn messenger', 14, 16);
INSERT INTO clanlite_smilies VALUES (89, '(trillian)', 'trilliangif.gif', 'trillian', 16, 16);
INSERT INTO clanlite_smilies VALUES (90, ':cowboy:', 'vache.gif', 'cowboy', 16, 16);
INSERT INTO clanlite_smilies VALUES (91, '8=', 'supper.gif', 'bordelle de ****', 16, 16);
INSERT INTO clanlite_smilies VALUES (92, 'Bp', 'lunette.gif', 'cool les mecs', 16, 16);
INSERT INTO clanlite_smilies VALUES (93, '&lt;(', 'crever.gif', 'fatiguer', 16, 16);
INSERT INTO clanlite_smilies VALUES (94, ':aie:', 'burq.gif', 'fais mal', 16, 16);
INSERT INTO clanlite_smilies VALUES (95, ':-/', 'heu.gif', 'arf', 16, 16);
INSERT INTO clanlite_smilies VALUES (96, '/!\\', 'attention.gif', 'Attention', 16, 16);
INSERT INTO clanlite_smilies VALUES (97, ':hug:', 'emot-hug.gif', 'je t\'aime toi', 40, 16);
INSERT INTO clanlite_smilies VALUES (98, ':gerbe:', 'emot-puke.gif', 'BUUuuuuuurg', 25, 16);
INSERT INTO clanlite_smilies VALUES (99, ':hihi:', 'sm11.gif', 'hihihihih', 16, 16);
INSERT INTO clanlite_smilies VALUES (100, ':prie:', 'prie.gif', 'Prie', 24, 16);
INSERT INTO clanlite_smilies VALUES (101, ':ho:', 'nonnn-sii.gif', 'hoo la grosse :-D', 16, 16);
INSERT INTO clanlite_smilies VALUES (102, ':bave:', 'emot-drool.gif', 'J\'en bave', 16, 16);
INSERT INTO clanlite_smilies VALUES (103, ':bye:', 'aa.gif', 'Bye mec', 16, 16);
INSERT INTO clanlite_user VALUES (1, 'Sneyers', 'narfight', 'narfight@lna.be', 'narfight@swing.be', '76434b3e23cdaf6f09d6e63f5b703e37', 'admin', 'Homme', 503190000, 'www.lna.be', 'dfgfdg', 1079625750, 'Jean-Pierre', 'BAR.gif', 0, 'fgfdg', 'Glandeur', 'scientist_center.jpeg', 10, ',,,,,,,,,', 0, '', '', 'Francais');
INSERT INTO clanlite_équipe VALUES (1, 'Sniper', 'Les Snipers tout simplement');
INSERT INTO clanlite_équipe VALUES (4, 'Rusher', 'ce sont ceux qui courtent relativement vite');